### PR TITLE
Include regular expression filters on more attributes

### PR DESCRIPTION
**Pull request by pauxus**
Full job name, folder name and job description.

I also cleaned up the TODO about the big if else block, which I refactored into the enum, this makes adding new values safer.

### CODE REVIEW

**Comment by bradflood** [comment]
@jglick  this PR appears to address an issue we are encountering, with the RegEx not being aware of folders.  Would it be possible to release?

**Comment by sf-nh** [comment]
I also would like the ability to use a regex against the fullname of a job.  We use multi branch pipeline, so we have many jobs with the same name, but in different folders, so currently regex against getName() is unhelpful.

**Comment by krulls** [comment]
@pauxus : Could you probably fix the conflicts that we see here after your PR has been built? I also would like to use the feature of filtering for jobs from folders.

**Comment by pauxus** [comment]
I am on it (completely forgot about this PR, actually).

Merge works so far, but I still have some strange effects with Mockito, will take a look at it soon.


Cheers,

Stephan
________________________________
Von: Stephan Krull <notifications@github.com>
Gesendet: Mittwoch, 17. Oktober 2018 17:46
An: jenkinsci/view-job-filters-plugin
Cc: Stephan Pauxberger; Mention
Betreff: Re: [jenkinsci/view-job-filters-plugin] Include regular expression filters on more attributes (#9)


@pauxus<https://github.com/pauxus> : Could you probably fix the conflicts that we see here after your PR has been built? I also would like to use the feature of filtering for jobs from folders.

**Comment by svenschoenung** [comment]
Thanks, I already merged this since I was the one who introduced all the conflicts by going rewrite crazy on the test suite.

The merge only contains the changes to the filter itself, not the tests. I made a separate commit where I added tests.

I'm hoping to publish this sometime next week. Since this is going to be feature release I want to get a couple of other things in as well.

**Pull request merged**
